version: '3'
services:
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beer
      MYSQL_USER:     root
      MYSQL_PASSWORD: root
    ports:
      - "40306:3306"
    tty: true
    volumes:
      - "./db:/var/lib/mysql:cached"
    restart: always